annotations:
  cluster.x-k8s.io/provider: infrastructure-aws
  cluster.x-k8s.io/v1beta1: v1beta1_v1beta2
  cluster.x-k8s.io/v1beta2: v1beta1_v1beta2
apiVersion: v2
appVersion: v2.10.0
description: A Helm chart for Cluster API provider AWS
name: cluster-api-provider-aws
type: application
version: 1.0.10
