apiVersion: v2
appVersion: "1763593473"
description: NVIDIA DOCA Platform Provisioning Controller
keywords:
- nvidia
- doca
- dpu
- provisioning
maintainers:
- name: NVIDIA
name: doca-provisioning
type: application
version: 42.1763593473.0-9ed585ae
