annotations:
  cluster.x-k8s.io/provider: infrastructure-tinkerbell
  cluster.x-k8s.io/v1beta1: v1beta1
apiVersion: v2
appVersion: 0.6.7
dependencies:
- condition: tinkerbell.enabled
  name: tinkerbell
  repository: oci://ghcr.io/tinkerbell/charts
  version: v0.22.0
description: A Helm chart for Cluster API Provider Tinkerbell
name: cluster-api-provider-tinkerbell
type: application
version: 1.0.0
