annotations:
  cluster.x-k8s.io/bootstrap-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/control-plane-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/infrastructure-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/provider: infrastructure-k0sproject-k0smotron, control-plane-k0sproject-k0smotron,
    bootstrap-k0sproject-k0smotron
apiVersion: v2
appVersion: v1.33.4+k0s.0
description: 'A KCM template to deploy a k0s cluster using k0smotron PooledRemoteMachine
  with bootstrapped control plane nodes. '
name: remote-cluster-standalone-cp
type: application
version: 1.1.1
