annotations:
  cluster.x-k8s.io/provider: infrastructure-vsphere
  cluster.x-k8s.io/v1beta1: v1beta1
  cluster.x-k8s.io/v1beta2: v1beta1
apiVersion: v2
appVersion: v1.14.0
description: A Helm chart for Cluster API provider vSphere
name: cluster-api-provider-vsphere
type: application
version: 1.0.6
