apiVersion: v2
appVersion: "1763681636"
description: NVIDIA DOCA Platform Provisioning Controller
keywords:
- nvidia
- doca
- dpu
- provisioning
maintainers:
- name: NVIDIA
name: doca-provisioning
type: application
version: 42.1763681636.0-3b211daf
