apiVersion: v2
appVersion: v1.1.1
dependencies:
- name: sveltos-crds
  repository: https://projectsveltos.github.io/helm-charts
  version: 1.1.1
- name: projectsveltos
  repository: https://projectsveltos.github.io/helm-charts
  version: 1.1.1
description: A Helm chart to refer the official projectsveltos helm chart
name: projectsveltos
type: application
version: 1.1.1
