annotations:
  cluster.x-k8s.io/bootstrap-kubeadm: v1beta1
  cluster.x-k8s.io/control-plane-hosted-control-plane: v1alpha1
  cluster.x-k8s.io/infrastructure-tinkerbell: v1beta1
  cluster.x-k8s.io/provider: infrastructure-tinkerbell, control-plane-hosted-control-plane,
    bootstrap-kubeadm
  k0rdent.mirantis.com/type: deployment
apiVersion: v2
appVersion: v1.34.2
description: 'A KCM template to deploy a Kubernetes cluster on Tinkerbell bare-metal
  with hosted control plane using cluster-api-provider-hosted-control-plane. '
name: tinkerbell-hcp-kubeadm
type: application
version: 1.0.0
