annotations:
  cluster.x-k8s.io/provider: bootstrap-kubeadm, control-plane-kubeadm
  cluster.x-k8s.io/v1beta1: v1beta1
  cluster.x-k8s.io/v1beta2: v1beta2
apiVersion: v2
appVersion: v1.11.3
description: A Helm chart for Cluster API Kubeadm Bootstrap and Control Plane Providers
name: cluster-api-provider-kubeadm
type: application
version: 1.1.0
