annotations:
  cluster.x-k8s.io/infrastructure-azure: v1beta1
  cluster.x-k8s.io/provider: infrastructure-azure
apiVersion: v2
description: 'A KCM template to deploy a cluster on AKS. '
name: azure-aks
type: application
version: 1.0.2
