apiVersion: v1
kind: Service
metadata:
  name: {{ include "doca-provisioning.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "doca-provisioning.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "doca-provisioning.selectorLabels" . | nindent 4 }}
