apiVersion: v2
appVersion: 1.6.2
description: A Helm chart for KubeVirt - Kubernetes Virtualization API and runtime
home: https://kubevirt.io/
keywords:
- kubevirt
- virtualization
- kubernetes
name: kubevirt
sources:
- https://github.com/kubevirt/kubevirt
type: application
version: 1.6.2
