annotations:
  cluster.x-k8s.io/provider: infrastructure-tinkerbell
  cluster.x-k8s.io/v1beta1: v1beta1
apiVersion: v2
appVersion: 0.6.8
dependencies:
- condition: tinkerbell.enabled
  name: tinkerbell
  repository: oci://ghcr.io/tinkerbell/charts
  version: v0.22.0
- condition: kubeVipCloudProvider.enabled
  name: kube-vip-cloud-provider
  repository: https://kube-vip.github.io/helm-charts
  version: 0.2.9
description: A Helm chart for Cluster API Provider Tinkerbell
name: cluster-api-provider-tinkerbell
type: application
version: 1.1.0
