annotations:
  commit: c2430c728b0d38df43a8ad38120c4faa613bddf0
  created: "2025-10-16T08:03:06+00:00"
  dpfVersion: v25.7.1
apiVersion: v2
appVersion: 0.1.0
dependencies:
- condition: multus.enabled
  name: multus
  repository: file://charts/multus
  version: 0.1.0
- condition: sriov-device-plugin.enabled
  name: sriov-device-plugin
  repository: file://charts/sriov-device-plugin
  version: 0.1.0
- condition: servicechainset-controller.enabled
  name: servicechainset-controller
  repository: file://charts/servicechainset-controller
  version: 0.1.0
- condition: nvidia-k8s-ipam.enabled
  name: nvidia-k8s-ipam
  repository: file://charts/nvidia-k8s-ipam
  version: 0.1.0
- condition: ovs-cni.enabled
  name: ovs-cni
  repository: file://charts/ovs-cni
  version: 0.1.0
- condition: sfc-controller.enabled
  name: sfc-controller
  repository: file://charts/sfc-controller
  version: 0.1.0
- condition: flannel.enabled
  name: flannel
  repository: https://flannel-io.github.io/flannel
  version: v0.26.5
description: A Helm chart for Kubernetes
name: dpu-networking
type: application
version: "1764113259"
