annotations:
  cluster.x-k8s.io/provider: infrastructure-azure
  cluster.x-k8s.io/v1beta1: v1beta1
apiVersion: v2
appVersion: v1.21.0
description: A Helm chart for Cluster API provider Azure
name: cluster-api-provider-azure
type: application
version: 1.0.7
