apiVersion: v2
appVersion: 1.1.1
description: A Helm chart for Projectsveltos CustomResourceDefinitions
icon: https://github.com/projectsveltos/sveltos/raw/main/docs/assets/logo.png
name: sveltos-crds
type: application
version: 1.1.1
