annotations:
  cluster.x-k8s.io/bootstrap-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/control-plane-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/infrastructure-nutanix: v1beta1
  cluster.x-k8s.io/provider: infrastructure-nutanix, control-plane-k0sproject-k0smotron,
    bootstrap-k0sproject-k0smotron
  k0rdent.mirantis.com/type: deployment
apiVersion: v2
appVersion: v1.7.0
description: 'A KCM template to deploy a k0s cluster on Nutanix with hosted control
  plane (k0smotron). '
home: https://github.com/k0rdent-oot/oot
keywords:
- k0rdent
- oot
- capi
- nutanix
- capx
- hcp
- k0s
- k0smotron
maintainers:
- name: k0rdent-oot maintainers
  url: https://github.com/k0rdent-oot/oot
name: nutanix-capx-hcp
sources:
- https://github.com/k0rdent-oot/oot
- https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix
type: application
version: 0.1.0
