{{ if not .Values.forDPUCluster }}
---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: servicechainset-rbac-and-crds
  namespace: dpf-operator-system
  labels:
    dpu.nvidia.com/component: servicechainset-rbac-and-crds
spec:
  helmChart:
    values:
      servicechainset-controller:
        forDPUCluster: true
        enabled: true
    source:
      repoURL: {{ .Values.chart.repoURL }}
      chart: {{ .Values.chart.chart }}
      version: {{ .Values.chart.version }}
{{ end }}