annotations:
  cluster.x-k8s.io/bootstrap-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/control-plane-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/infrastructure-aws: v1beta2
  cluster.x-k8s.io/provider: infrastructure-aws, control-plane-k0sproject-k0smotron,
    bootstrap-k0sproject-k0smotron
apiVersion: v2
appVersion: v1.32.6+k0s.0
description: 'A KCM template to deploy a k8s cluster on AWS with control plane components
  within the management cluster. '
name: aws-hosted-cp
type: application
version: 1.0.12
