apiVersion: v2
appVersion: "1763749572"
description: NVIDIA DOCA Platform Provisioning Controller
keywords:
- nvidia
- doca
- dpu
- provisioning
maintainers:
- name: NVIDIA
name: doca-provisioning
type: application
version: 42.1763749572.0-7e584ed0
