apiVersion: v2
appVersion: 6f323f72
description: NVIDIA DOCA Platform Provisioning Controller
keywords:
- nvidia
- doca
- dpu
- provisioning
maintainers:
- name: NVIDIA
name: doca-provisioning
type: application
version: 42.1763591706.0-6f323f72
