apiVersion: v2
appVersion: "1763661172"
description: NVIDIA DOCA Platform Provisioning Controller
keywords:
- nvidia
- doca
- dpu
- provisioning
maintainers:
- name: NVIDIA
name: doca-provisioning
type: application
version: 42.1763661172.0-0aabedbc
