annotations:
  cluster.x-k8s.io/v1beta1: ""
  cluster.x-k8s.io/v1beta2: ""
apiVersion: v2
appVersion: v1.12.1
description: A Helm chart for Cluster API core components
name: cluster-api
type: application
version: 1.1.0
