apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: iprequest
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sfc-controller.labels" . | nindent 4 }}
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "type": "dummy",
      "ipam": {
        "type": "nv-ipam"
      }
    }
