{{- if .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "doca-provisioning.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "doca-provisioning.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "doca-provisioning.selectorLabels" . | nindent 4 }}
{{- end }}
